// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzfA-1UdZ5PRMqFhySS1mt1t9Afofgi8',
    appId: '1:303908236194:web:05a8cb2e945783e81120fb',
    messagingSenderId: '303908236194',
    projectId: 'sleeping-app-2',
    authDomain: 'sleeping-app-2.firebaseapp.com',
    storageBucket: 'sleeping-app-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuApWtSf6xihnGAU_5m1Ut3u2fGKdyTfM',
    appId: '1:303908236194:android:487b1e8c5205075b1120fb',
    messagingSenderId: '303908236194',
    projectId: 'sleeping-app-2',
    storageBucket: 'sleeping-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3robjJE8WXxdfetKE6yQXJn_p88cdd1w',
    appId: '1:303908236194:ios:37c5c4a3e98f44441120fb',
    messagingSenderId: '303908236194',
    projectId: 'sleeping-app-2',
    storageBucket: 'sleeping-app-2.appspot.com',
    iosBundleId: 'com.example.sleepingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3robjJE8WXxdfetKE6yQXJn_p88cdd1w',
    appId: '1:303908236194:ios:42f0c5a2d69842211120fb',
    messagingSenderId: '303908236194',
    projectId: 'sleeping-app-2',
    storageBucket: 'sleeping-app-2.appspot.com',
    iosBundleId: 'com.example.sleepingApp.RunnerTests',
  );
}
